/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/email/verify/send": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 이메일 인증 코드 발송
         * @description 회원가입 전 이메일 소유 확인용 6자리 코드를 발송한다. 재발송 쿨다운 60초.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    /**
                     * @example {
                     *       "email": "user@example.com"
                     *     }
                     */
                    "application/json": components["schemas"]["SendVerificationRequest"];
                };
            };
            responses: {
                /** @description 코드 발송 성공 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponseEmpty"];
                    };
                };
                422: components["responses"]["ValidationError_422"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/email/verify/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 이메일 인증 코드 확인
         * @description 발송된 6자리 코드를 검증하고 30분간 "인증 완료" 상태를 유지한다.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    /**
                     * @example {
                     *       "email": "user@example.com",
                     *       "code": "123456"
                     *     }
                     */
                    "application/json": components["schemas"]["VerifyCodeRequest"];
                };
            };
            responses: {
                /** @description 인증 성공 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponseEmpty"];
                    };
                };
                401: components["responses"]["Unauthorized_401"];
                422: components["responses"]["ValidationError_422"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 회원가입
         * @description 이메일 인증 완료 상태에서만 호출 가능.
         *     성공 시 access token은 body, refresh token은 HttpOnly Cookie로 발급된다.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    /**
                     * @example {
                     *       "email": "user@example.com",
                     *       "password": "strongPass1!",
                     *       "passwordConfirm": "strongPass1!",
                     *       "country": "KR",
                     *       "region": null
                     *     }
                     */
                    "application/json": components["schemas"]["RegisterRequest"];
                };
            };
            responses: {
                /** @description 가입 성공 */
                201: {
                    headers: {
                        /** @description `refresh_token` HttpOnly cookie (7d) */
                        "Set-Cookie"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponseToken"];
                    };
                };
                400: components["responses"]["BadRequest_400"];
                409: components["responses"]["Conflict_409"];
                422: components["responses"]["ValidationError_422"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 이메일 + 비밀번호 로그인 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    /**
                     * @example {
                     *       "email": "user@example.com",
                     *       "password": "strongPass1!"
                     *     }
                     */
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description 로그인 성공 */
                200: {
                    headers: {
                        /** @description `refresh_token` HttpOnly cookie (7d) */
                        "Set-Cookie"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponseToken"];
                    };
                };
                401: components["responses"]["Unauthorized_401"];
                422: components["responses"]["ValidationError_422"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/token/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Access Token 재발급
         * @description `refresh_token` Cookie를 사용해 새 access token + 새 refresh token을 발급한다.
         *     rotation 방식으로 이전 refresh token은 즉시 폐기된다.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 재발급 성공 */
                200: {
                    headers: {
                        /** @description 회전된 새 `refresh_token` Cookie */
                        "Set-Cookie"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponseToken"];
                    };
                };
                401: components["responses"]["Unauthorized_401"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 로그아웃
         * @description refresh token을 폐기하고 쿠키를 삭제한다.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 로그아웃 성공 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponseEmpty"];
                    };
                };
                401: components["responses"]["Unauthorized_401"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 내 정보 조회 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 조회 성공 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponseUser"];
                    };
                };
                401: components["responses"]["Unauthorized_401"];
                404: components["responses"]["NotFound_404"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 프로필 수정 */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    /**
                     * @example {
                     *       "display_name": "변경된 이름"
                     *     }
                     */
                    "application/json": components["schemas"]["UpdateProfileRequest"];
                };
            };
            responses: {
                /** @description 수정 성공 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponseUser"];
                    };
                };
                401: components["responses"]["Unauthorized_401"];
                404: components["responses"]["NotFound_404"];
            };
        };
        trace?: never;
    };
    "/auth/oauth/{provider}/authorize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * OAuth 인증 시작 (리다이렉트)
         * @description 해당 provider의 OAuth 인증 페이지로 **302 Redirect**한다.
         *     프론트에서 이 URL을 새 창/팝업으로 열어 사용한다.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    provider: components["parameters"]["OAuthProviderPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OAuth provider로 리다이렉트 */
                302: {
                    headers: {
                        /** @description provider의 authorize URL */
                        Location?: string;
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/oauth/{provider}/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * OAuth 콜백 (provider → 백엔드)
         * @description OAuth provider가 redirect로 호출하는 콜백. **클라이언트가 직접 호출하지 않는다.**
         *
         *     응답은 HTML이며 팝업 창에서 `window.opener.postMessage()`로 부모 창에 결과를 전달한다.
         *
         *     ### 분기
         *     - **기존 사용자** → `oauth_success` + access token + `refresh_token` HttpOnly Cookie
         *     - **신규 사용자** (OAuth 첫 사용) → `oauth_onboarding_required` + `onboarding_token` HttpOnly Cookie (TTL 30분).
         *       FE는 `/onboarding` 페이지로 이동해 `POST /auth/oauth/onboarding`에서 국가 정보를 추가 입력해 가입을 완료한다.
         *
         *     ```js
         *     // 기존 사용자
         *     { type: "oauth_success", access_token: "..." }
         *     // 신규 사용자
         *     { type: "oauth_onboarding_required" }
         *     // 실패
         *     { type: "oauth_error", error: "<ERROR_CODE>" }
         *     ```
         */
        get: {
            parameters: {
                query?: {
                    /** @description provider가 발급한 인가 코드 */
                    code?: string;
                    /** @description CSRF 방지용 state (initiate 시 발급된 값) */
                    state?: string;
                    /** @description provider가 에러를 반환한 경우의 코드 */
                    error?: string;
                };
                header?: never;
                path: {
                    provider: components["parameters"]["OAuthProviderPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description HTML 응답 (postMessage 스크립트 포함) */
                200: {
                    headers: {
                        /**
                         * @description 기존 사용자 → `refresh_token` HttpOnly Cookie (7d)
                         *     신규 사용자 → `onboarding_token` HttpOnly Cookie (30min)
                         */
                        "Set-Cookie"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "text/html": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/oauth/onboarding": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * OAuth 신규 사용자 온보딩 완료
         * @description OAuth 콜백 단계에서 `onboarding_token` HttpOnly Cookie를 받은 신규 사용자가 국가 정보를
         *     추가 입력해 가입을 완료한다.
         *
         *     - 다중 tz 국가(US/CA/RU/AU/BR/MX/ID/AR/CL/KZ/MN)는 `region` 필수 (ISO 3166-2: 예 `US-CA`)
         *     - 단일 tz 국가는 `region` 생략 가능
         *     - 성공 시 `onboarding_token` Cookie 삭제 + `refresh_token` Cookie + access token body
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["OnboardingCompleteRequest"];
                };
            };
            responses: {
                /** @description 가입 완료 */
                201: {
                    headers: {
                        /** @description `refresh_token` HttpOnly cookie (7d) + `onboarding_token` 삭제 */
                        "Set-Cookie"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponseToken"];
                    };
                };
                401: components["responses"]["Unauthorized_401"];
                409: components["responses"]["Conflict_409"];
                422: components["responses"]["ValidationError_422"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/todos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 할 일 목록 조회
         * @description 쿼리 파라미터에 따라 모드가 결정된다:
         *     - `dateKey` 단독 → 해당 일자의 할 일
         *     - `from` + `to` → 기간 범위 조회
         *     - 둘 다 없으면 빈 배열 반환
         */
        get: {
            parameters: {
                query?: {
                    /** @example 2026-05-31 */
                    dateKey?: string;
                    from?: string;
                    to?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 조회 성공 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponseTodoList"];
                    };
                };
                401: components["responses"]["Unauthorized_401"];
            };
        };
        put?: never;
        /** 할 일 생성 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    /**
                     * @example {
                     *       "title": "회의 자료 준비",
                     *       "date_key": "2026-05-31",
                     *       "description": "회의 슬라이드 작성",
                     *       "status": "not-start"
                     *     }
                     */
                    "application/json": components["schemas"]["TodoCreateRequest"];
                };
            };
            responses: {
                /** @description 생성 성공 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponseTodo"];
                    };
                };
                401: components["responses"]["Unauthorized_401"];
                422: components["responses"]["ValidationError_422"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/todos/{todo_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example todo_01HXYZ... */
                todo_id: components["parameters"]["TodoIdPath"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 할 일 삭제 */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @example todo_01HXYZ... */
                    todo_id: components["parameters"]["TodoIdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 삭제 성공 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponseEmpty"];
                    };
                };
                401: components["responses"]["Unauthorized_401"];
                404: components["responses"]["NotFound_404"];
            };
        };
        options?: never;
        head?: never;
        /** 할 일 수정 (부분) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @example todo_01HXYZ... */
                    todo_id: components["parameters"]["TodoIdPath"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    /**
                     * @example {
                     *       "status": "done"
                     *     }
                     */
                    "application/json": components["schemas"]["TodoUpdateRequest"];
                };
            };
            responses: {
                /** @description 수정 성공 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponseTodo"];
                    };
                };
                401: components["responses"]["Unauthorized_401"];
                404: components["responses"]["NotFound_404"];
                409: components["responses"]["Conflict_409"];
                422: components["responses"]["ValidationError_422"];
            };
        };
        trace?: never;
    };
    "/entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 회고 엔트리 목록 조회
         * @description 회고 종류·기간 필터로 조회한다.
         */
        get: {
            parameters: {
                query?: {
                    retroType?: components["schemas"]["RetroType"];
                    from?: string;
                    to?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 조회 성공 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponseEntryList"];
                    };
                };
                401: components["responses"]["Unauthorized_401"];
            };
        };
        put?: never;
        /** 회고 엔트리 생성 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    /**
                     * @example {
                     *       "date_key": "2026-05-31",
                     *       "title": "5월 31일 회고",
                     *       "content": "오늘은 ...",
                     *       "retro_type": "daily"
                     *     }
                     */
                    "application/json": components["schemas"]["EntryCreateRequest"];
                };
            };
            responses: {
                /** @description 생성 성공 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponseEntry"];
                    };
                };
                401: components["responses"]["Unauthorized_401"];
                409: components["responses"]["Conflict_409"];
                422: components["responses"]["ValidationError_422"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entries/{entry_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example entry_01HXYZ... */
                entry_id: components["parameters"]["EntryIdPath"];
            };
            cookie?: never;
        };
        /** 단일 엔트리 조회 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @example entry_01HXYZ... */
                    entry_id: components["parameters"]["EntryIdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 조회 성공 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponseEntry"];
                    };
                };
                401: components["responses"]["Unauthorized_401"];
                404: components["responses"]["NotFound_404"];
            };
        };
        /**
         * 엔트리 Upsert
         * @description 존재하면 수정, 없으면 생성한다 (idempotent).
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @example entry_01HXYZ... */
                    entry_id: components["parameters"]["EntryIdPath"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["EntryUpsertRequest"];
                };
            };
            responses: {
                /** @description Upsert 성공 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponseEntry"];
                    };
                };
                401: components["responses"]["Unauthorized_401"];
                422: components["responses"]["ValidationError_422"];
            };
        };
        post?: never;
        /** 엔트리 삭제 */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @example entry_01HXYZ... */
                    entry_id: components["parameters"]["EntryIdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 삭제 성공 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponseEmpty"];
                    };
                };
                401: components["responses"]["Unauthorized_401"];
                404: components["responses"]["NotFound_404"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/summaries/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * AI 요약 생성 요청 (비동기)
         * @description Celery worker(`ai_tasks` 큐, priority=9)로 요약 작업을 enqueue하고 **즉시 202를 반환**한다.
         *
         *     - 같은 기간에 PENDING/IN_PROGRESS 요약이 있으면 `409 RETRO_SUMMARY_IN_PROGRESS` 반환
         *     - COMPLETED 요약이 있으면 그대로 반환 (재실행하지 않음)
         *     - FAILED 요약은 자동으로 PENDING 리셋 후 재실행
         *     - Gemini 호출은 rate_limit `60/min` 적용
         */
        post: {
            parameters: {
                query: {
                    type: components["schemas"]["SummaryType"];
                    /**
                     * @description 생략 시 직전 기간 자동 계산 (지난 주 월~일 / 지난 달 / 작년).
                     *     지정 시 해당 기간의 시작일 (월요일/1일/1월1일).
                     */
                    periodStart?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 요청 접수 */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponseSummary"];
                    };
                };
                401: components["responses"]["Unauthorized_401"];
                409: components["responses"]["Conflict_409"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/summaries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 요약 목록 조회 (타입별) */
        get: {
            parameters: {
                query: {
                    type: components["schemas"]["SummaryType"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 조회 성공 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponseSummaryList"];
                    };
                };
                401: components["responses"]["Unauthorized_401"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/summaries/{summary_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example summ_01HXYZ... */
                summary_id: components["parameters"]["SummaryIdPath"];
            };
            cookie?: never;
        };
        /** 단일 요약 조회 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @example summ_01HXYZ... */
                    summary_id: components["parameters"]["SummaryIdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 조회 성공 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponseSummary"];
                    };
                };
                401: components["responses"]["Unauthorized_401"];
                404: components["responses"]["NotFound_404"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/summaries/{summary_id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example summ_01HXYZ... */
                summary_id: components["parameters"]["SummaryIdPath"];
            };
            cookie?: never;
        };
        /**
         * 요약 완료 SSE 스트림
         * @description Celery worker가 요약 처리를 완료할 때까지 대기하며, 완료 시 단일 SSE 이벤트를 전송하고 종료한다.
         *
         *     - **타임아웃**: 5분 (이후 `{"status": "timeout"}` 전송)
         *     - 이미 완료/실패 상태면 즉시 이벤트 전송 후 종료
         *
         *     ### 이벤트 페이로드
         *     ```
         *     data: {"status": "completed", "summary_id": "summ_..."}
         *     data: {"status": "failed",    "summary_id": "summ_..."}
         *     data: {"status": "timeout",   "summary_id": "summ_..."}
         *     data: {"status": "error",     "error": "<ERROR_CODE>"}
         *     ```
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @example summ_01HXYZ... */
                    summary_id: components["parameters"]["SummaryIdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description SSE 스트림 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/event-stream": string;
                    };
                };
                401: components["responses"]["Unauthorized_401"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 알림 실시간 SSE 스트림
         * @description Redis pub/sub 채널 `notifications:{user_id}`를 구독하여 새 알림을 실시간 푸시한다.
         *
         *     - **타임아웃**: 5분 (이후 `{"type": "timeout"}` 전송)
         *     - 페이로드는 `NotificationResponse`와 동일 + (`type`/`category` 포함)
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description SSE 스트림 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/event-stream": string;
                    };
                };
                401: components["responses"]["Unauthorized_401"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 알림 목록 조회 */
        get: {
            parameters: {
                query?: {
                    unreadOnly?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 조회 성공 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponseNotificationList"];
                    };
                };
                401: components["responses"]["Unauthorized_401"];
            };
        };
        put?: never;
        post?: never;
        /** 알림 일괄 삭제 */
        delete: {
            parameters: {
                query?: {
                    /** @description true면 읽은 알림만 삭제, false면 전체 삭제 */
                    readOnly?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 삭제 성공 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponseEmpty"];
                    };
                };
                401: components["responses"]["Unauthorized_401"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/read-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 모든 알림 읽음 처리 */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 성공 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponseEmpty"];
                    };
                };
                401: components["responses"]["Unauthorized_401"];
            };
        };
        trace?: never;
    };
    "/notifications/{notification_id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example noti_01HXYZ... */
                notification_id: components["parameters"]["NotificationIdPath"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 단일 알림 읽음 처리 */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @example noti_01HXYZ... */
                    notification_id: components["parameters"]["NotificationIdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 성공 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponseEmpty"];
                    };
                };
                401: components["responses"]["Unauthorized_401"];
                404: components["responses"]["NotFound_404"];
            };
        };
        trace?: never;
    };
    "/notifications/{notification_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example noti_01HXYZ... */
                notification_id: components["parameters"]["NotificationIdPath"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 단일 알림 삭제 */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @example noti_01HXYZ... */
                    notification_id: components["parameters"]["NotificationIdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 삭제 성공 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponseEmpty"];
                    };
                };
                401: components["responses"]["Unauthorized_401"];
                404: components["responses"]["NotFound_404"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 유저 설정 조회 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 조회 성공 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponseSettings"];
                    };
                };
                401: components["responses"]["Unauthorized_401"];
            };
        };
        /** 유저 설정 수정 (전체 교체) */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    /**
                     * @example {
                     *       "locale": "ko",
                     *       "autoSummaryWeekly": true,
                     *       "autoSummaryMonthly": true,
                     *       "autoSummaryYearly": false,
                     *       "notificationRetentionDays": 30
                     *     }
                     */
                    "application/json": components["schemas"]["UpdateSettingsRequest"];
                };
            };
            responses: {
                /** @description 수정 성공 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponseSettings"];
                    };
                };
                401: components["responses"]["Unauthorized_401"];
                422: components["responses"]["ValidationError_422"];
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings/country": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 국가/하위지역 변경 — timezone 자동 재계산
         * @description 사용자 국가를 변경하면 backend가 country/region 조합으로 timezone을 재계산해 같이 저장한다.
         *     AI 자동 요약 트리거 시간(현지 1am)도 새 timezone 기준으로 자동 갱신된다.
         *
         *     - 다중 tz 국가는 `region`(ISO 3166-2) 필수
         *     - 단일 tz 국가는 `region` 생략 가능
         *     - 임의로 timezone만 단독 변경하려면 `PATCH /settings/timezone` 사용
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateCountryRequest"];
                };
            };
            responses: {
                /** @description 수정 성공 (timezone 포함된 user 응답) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponseUser"];
                    };
                };
                401: components["responses"]["Unauthorized_401"];
                404: components["responses"]["NotFound_404"];
                422: components["responses"]["ValidationError_422"];
            };
        };
        trace?: never;
    };
    "/settings/timezone": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Timezone 단독 변경 (country는 유지)
         * @description country를 바꾸지 않고 timezone만 별도로 override한다. 해외 출장/임시 거주 등의 케이스용.
         *     IANA 식별자(`Asia/Seoul`, `America/Los_Angeles` 등) 형식이어야 한다.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    /**
                     * @example {
                     *       "timezone": "America/Los_Angeles"
                     *     }
                     */
                    "application/json": components["schemas"]["UpdateTimezoneRequest"];
                };
            };
            responses: {
                /** @description 수정 성공 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponseUser"];
                    };
                };
                401: components["responses"]["Unauthorized_401"];
                404: components["responses"]["NotFound_404"];
                422: components["responses"]["ValidationError_422"];
            };
        };
        trace?: never;
    };
    "/github/repositories/available": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * GitHub에서 사용자 저장소 목록 조회
         * @description OAuth로 연결된 GitHub 계정의 모든 **public** 저장소 목록을 GitHub API에서 직접 가져온다.
         *     DB 저장은 하지 않음 (연결 후보 표시 용도).
         *     - `public_repo` scope 기준
         *     - 페이지네이션 자동 처리 (최대 2000개)
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 조회 성공 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponseAvailableRepoList"];
                    };
                };
                400: components["responses"]["BadRequest_400"];
                401: components["responses"]["Unauthorized_401"];
                429: components["responses"]["RateLimited_429"];
                503: components["responses"]["ServiceUnavailable_503"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/github/repositories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 연결된 저장소 목록 조회
         * @description DB에 저장된, 현재 사용자가 연결한 GitHub 저장소 목록.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 조회 성공 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponseRepositoryList"];
                    };
                };
                401: components["responses"]["Unauthorized_401"];
            };
        };
        put?: never;
        /**
         * 특정 저장소 1개 연결
         * @description `githubRepoId`로 식별되는 저장소를 사용자 계정에 연결한다.
         *     백엔드가 GitHub API에서 해당 저장소 메타데이터를 직접 조회해 저장 (위·변조 방지).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    /**
                     * @example {
                     *       "githubRepoId": 1296269
                     *     }
                     */
                    "application/json": components["schemas"]["LinkRepositoryRequest"];
                };
            };
            responses: {
                /** @description 연결 성공 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponseRepository"];
                    };
                };
                400: components["responses"]["BadRequest_400"];
                401: components["responses"]["Unauthorized_401"];
                404: components["responses"]["NotFound_404"];
                409: components["responses"]["Conflict_409"];
                422: components["responses"]["ValidationError_422"];
                429: components["responses"]["RateLimited_429"];
            };
        };
        /**
         * 모든 저장소 연결 해제
         * @description 현재 사용자의 모든 GitHub 저장소 연결을 일괄 삭제.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 삭제 성공 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponseEmpty"];
                    };
                };
                401: components["responses"]["Unauthorized_401"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/github/repositories/sync-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * GitHub 저장소 전체 일괄 연결 (1회 sync)
         * @description 호출 시점의 GitHub 저장소 목록을 모두 가져와 일괄 연결한다 (idempotent upsert).
         *     이후 새로 생긴 repo는 사용자가 다시 호출해야 추가됨 (자동 갱신 없음).
         *     이미 연결된 저장소는 유지되며, 메타데이터가 바뀌었다면 갱신된다.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description sync 성공. 응답에는 현재 시점에 연결된 모든 저장소 목록이 담긴다. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponseRepositoryList"];
                    };
                };
                400: components["responses"]["BadRequest_400"];
                401: components["responses"]["Unauthorized_401"];
                429: components["responses"]["RateLimited_429"];
                503: components["responses"]["ServiceUnavailable_503"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/github/repositories/{repository_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example ghrepo_01HXYZ... */
                repository_id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 단일 저장소 연결 해제 */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @example ghrepo_01HXYZ... */
                    repository_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 해제 성공 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponseEmpty"];
                    };
                };
                401: components["responses"]["Unauthorized_401"];
                404: components["responses"]["NotFound_404"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApiResponseEmpty: {
            /** @enum {string} */
            status: "success" | "accepted";
            /** @example OK */
            code: string;
            data: null;
        };
        ErrorResponse: {
            /** @enum {string} */
            status: "error";
            /** @description 도메인 에러 코드 (예 `AUTH_TOKEN_EXPIRED`, `TODO_NOT_FOUND`, `VALIDATION_ERROR`) */
            code: string;
            data: null;
            details?: {
                field?: string;
                message?: string;
            }[];
        };
        /** @enum {string} */
        OAuthProvider: "github" | "google";
        /**
         * @description 회고 엔트리 종류
         * @enum {string}
         */
        RetroType: "daily" | "weekly" | "monthly" | "yearly";
        /**
         * @description AI 요약 주기
         * @enum {string}
         */
        SummaryType: "weekly" | "monthly" | "annual";
        /** @enum {string} */
        TodoStatus: "not-start" | "in-progress" | "done";
        /** @enum {string} */
        SummaryStatus: "pending" | "in_progress" | "completed" | "failed";
        /** @enum {string} */
        NotificationType: "info" | "success" | "warning" | "error";
        /** @enum {string} */
        NotificationCategory: "sync" | "summary" | "system";
        SendVerificationRequest: {
            /** Format: email */
            email: string;
        };
        VerifyCodeRequest: {
            /** Format: email */
            email: string;
            /** @description 영문 대문자 또는 숫자 6자리 (서버에서 strip + upper 정규화 후 검증) */
            code: string;
        };
        RegisterRequest: {
            /** Format: email */
            email: string;
            password: string;
            passwordConfirm: string;
            /**
             * @description ISO 3166-1 alpha-2 국가 코드 (예: `KR`, `US`, `JP`).
             *     다중 tz 국가(US/CA/RU/AU/BR/MX/ID/AR/CL/KZ/MN)는 `region` 필수.
             */
            country: string;
            /**
             * @description ISO 3166-2 하위지역 코드 (예: `US-CA`, `CA-ON`).
             *     단일 tz 국가는 생략 가능 (`null`).
             */
            region?: string | null;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        UpdateProfileRequest: {
            display_name?: string | null;
        };
        OnboardingCompleteRequest: {
            country: string;
            region?: string | null;
        };
        UpdateCountryRequest: {
            country: string;
            region?: string | null;
        };
        UpdateTimezoneRequest: {
            /**
             * @description IANA timezone identifier
             * @example Asia/Seoul
             */
            timezone: string;
        };
        TokenResponse: {
            accessToken: string;
        };
        UserResponse: {
            id: string;
            /** Format: email */
            email: string;
            /** @example KR */
            country: string;
            /** @example null */
            region?: string | null;
            /**
             * @description IANA timezone identifier — AI 자동 요약은 이 tz 기준 "현지 새벽 1시"에 트리거됨
             * @example Asia/Seoul
             */
            timezone: string;
        };
        ApiResponseToken: components["schemas"]["ApiResponseEmpty"] & {
            data?: components["schemas"]["TokenResponse"];
        };
        ApiResponseUser: components["schemas"]["ApiResponseEmpty"] & {
            data?: components["schemas"]["UserResponse"];
        };
        TodoCreateRequest: {
            title: string;
            date_key: string;
            /** @default  */
            description: string;
            /** @default not-start */
            status: components["schemas"]["TodoStatus"];
        };
        TodoUpdateRequest: {
            title?: string | null;
            status?: components["schemas"]["TodoStatus"];
            description?: string | null;
            date_key?: string | null;
        };
        TodoResponse: {
            id: string;
            user_id: string;
            title: string;
            status: components["schemas"]["TodoStatus"];
            date_key: string;
            description: string;
            /** @description status == "done" */
            completed: boolean;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at?: string | null;
            /** Format: date-time */
            completed_at?: string | null;
        };
        ApiResponseTodo: components["schemas"]["ApiResponseEmpty"] & {
            data?: components["schemas"]["TodoResponse"];
        };
        ApiResponseTodoList: components["schemas"]["ApiResponseEmpty"] & {
            data?: components["schemas"]["TodoResponse"][];
        };
        EntryCreateRequest: {
            date_key: string;
            title: string;
            /** @default  */
            content: string;
            /** @default daily */
            retro_type: components["schemas"]["RetroType"];
        };
        EntryUpsertRequest: components["schemas"]["EntryCreateRequest"];
        EntryResponse: {
            id: string;
            user_id: string;
            date_key: string;
            title: string;
            content: string;
            retro_type: components["schemas"]["RetroType"];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at?: string | null;
        };
        ApiResponseEntry: components["schemas"]["ApiResponseEmpty"] & {
            data?: components["schemas"]["EntryResponse"];
        };
        ApiResponseEntryList: components["schemas"]["ApiResponseEmpty"] & {
            data?: components["schemas"]["EntryResponse"][];
        };
        SummaryContentResponse: {
            achievements?: string[];
            challenges?: string[];
            learnings?: string[];
            next_focus?: string[];
        };
        SummaryResponse: {
            id: string;
            user_id: string;
            summary_type: components["schemas"]["SummaryType"];
            /** Format: date */
            period_start: string;
            /** Format: date */
            period_end: string;
            status: components["schemas"]["SummaryStatus"];
            content?: components["schemas"]["SummaryContentResponse"];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at?: string | null;
        };
        ApiResponseSummary: components["schemas"]["ApiResponseEmpty"] & {
            data?: components["schemas"]["SummaryResponse"];
        };
        ApiResponseSummaryList: components["schemas"]["ApiResponseEmpty"] & {
            data?: components["schemas"]["SummaryResponse"][];
        };
        NotificationResponse: {
            id: string;
            type: components["schemas"]["NotificationType"];
            category: components["schemas"]["NotificationCategory"];
            title: string;
            message: string;
            is_read: boolean;
            /** Format: date-time */
            created_at: string;
        };
        ApiResponseNotificationList: components["schemas"]["ApiResponseEmpty"] & {
            data?: components["schemas"]["NotificationResponse"][];
        };
        UpdateSettingsRequest: {
            /** @default ko */
            locale: string;
            /** @default false */
            autoSummaryWeekly: boolean;
            /** @default false */
            autoSummaryMonthly: boolean;
            /** @default false */
            autoSummaryYearly: boolean;
            /** @default 30 */
            notificationRetentionDays: number;
            /** Format: date-time */
            lastScheduleCheckAt?: string | null;
        };
        SettingsResponse: {
            locale: string;
            autoSummaryWeekly: boolean;
            autoSummaryMonthly: boolean;
            autoSummaryYearly: boolean;
            notificationRetentionDays: number;
            /** Format: date-time */
            lastScheduleCheckAt?: string | null;
        };
        ApiResponseSettings: components["schemas"]["ApiResponseEmpty"] & {
            data?: components["schemas"]["SettingsResponse"];
        };
        LinkRepositoryRequest: {
            /**
             * Format: int64
             * @description GitHub의 numeric repository ID
             */
            githubRepoId: number;
        };
        RepositoryResponse: {
            /** @description 백엔드에서 발급한 연결 ID (`ghrepo_...`) */
            id: string;
            /** Format: int64 */
            githubRepoId: number;
            owner: string;
            name: string;
            /** @example octocat/Hello-World */
            fullName: string;
            isPrivate: boolean;
            /** @example main */
            defaultBranch: string;
            /** Format: uri */
            htmlUrl: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt?: string | null;
        };
        AvailableRepositoryResponse: {
            /** Format: int64 */
            githubRepoId: number;
            owner: string;
            name: string;
            fullName: string;
            isPrivate: boolean;
            defaultBranch: string;
            /** Format: uri */
            htmlUrl: string;
        };
        ApiResponseRepository: components["schemas"]["ApiResponseEmpty"] & {
            data?: components["schemas"]["RepositoryResponse"];
        };
        ApiResponseRepositoryList: components["schemas"]["ApiResponseEmpty"] & {
            data?: components["schemas"]["RepositoryResponse"][];
        };
        ApiResponseAvailableRepoList: components["schemas"]["ApiResponseEmpty"] & {
            data?: components["schemas"]["AvailableRepositoryResponse"][];
        };
    };
    responses: {
        /** @description 잘못된 요청 (도메인 invalid state) */
        BadRequest_400: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "status": "error",
                 *       "code": "RETRO_SUMMARY_INVALID_STATE",
                 *       "data": null,
                 *       "details": []
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /**
         * @description 인증 실패. 가능한 코드:
         *     - `AUTH_TOKEN_EXPIRED` — access token 만료 (**FE 자동 refresh 트리거**)
         *     - `AUTH_TOKEN_INVALID` — 토큰 누락 / 형식 오류 / 서명 불일치 / type mismatch
         *     - `AUTH_INVALID_CREDENTIALS` — 이메일/비밀번호 불일치
         *     - `AUTH_REFRESH_TOKEN_INVALID` / `AUTH_REFRESH_TOKEN_REVOKED` — refresh 실패
         *     - `AUTH_OAUTH_STATE_INVALID` — OAuth state 검증 실패
         *     - `AUTH_ONBOARDING_TOKEN_INVALID` — onboarding cookie 누락
         *     - `AUTH_ONBOARDING_TOKEN_EXPIRED` — onboarding TTL(30분) 만료
         *     - `GITHUB_TOKEN_INVALID` — GitHub OAuth 토큰 만료/폐기 (FE는 GitHub OAuth 재인증 유도)
         */
        Unauthorized_401: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "status": "error",
                 *       "code": "AUTH_TOKEN_EXPIRED",
                 *       "data": null,
                 *       "details": []
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 리소스를 찾을 수 없음 */
        NotFound_404: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "status": "error",
                 *       "code": "TODO_NOT_FOUND",
                 *       "data": null,
                 *       "details": []
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 상태 충돌 (중복·이미 진행 중 등) */
        Conflict_409: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "status": "error",
                 *       "code": "USER_EMAIL_DUPLICATED",
                 *       "data": null,
                 *       "details": []
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 요청 검증 실패 (Pydantic) */
        ValidationError_422: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "status": "error",
                 *       "code": "VALIDATION_ERROR",
                 *       "data": null,
                 *       "details": [
                 *         {
                 *           "field": "email",
                 *           "message": "value is not a valid email address"
                 *         }
                 *       ]
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description GitHub API rate limit 초과. 잠시 후 재시도. */
        RateLimited_429: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "status": "error",
                 *       "code": "GITHUB_RATE_LIMITED",
                 *       "data": null,
                 *       "details": []
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 외부 서비스(GitHub API) 일시적 장애 */
        ServiceUnavailable_503: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "status": "error",
                 *       "code": "GITHUB_API_UNAVAILABLE",
                 *       "data": null,
                 *       "details": []
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        /** @example todo_01HXYZ... */
        TodoIdPath: string;
        /** @example entry_01HXYZ... */
        EntryIdPath: string;
        /** @example summ_01HXYZ... */
        SummaryIdPath: string;
        /** @example noti_01HXYZ... */
        NotificationIdPath: string;
        OAuthProviderPath: components["schemas"]["OAuthProvider"];
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
